name = "WaveOpticsPropagation"
uuid = "c4c7a1f9-3adc-4a73-843a-d378b6c86436"
authors = ["Felix Wechsler (roflmaostc) <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
IndexFunArrays = "613c443e-d742-454e-bfc6-1d7f8dd76566"
NDTools = "98581153-e998-4eef-8d0d-5ec2c052313d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CUDA = "4"
ChainRulesCore = "1"
EllipsisNotation = "1"
FFTW = "1"
FourierTools = "0.4.1"
IndexFunArrays = "0.2"
NDTools = "0.5"
Zygote = "0.6"
julia = "1.8"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
IndexFunArrays = "613c443e-d742-454e-bfc6-1d7f8dd76566"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "ChainRulesTestUtils", "Zygote", "IndexFunArrays", "Markdown", "InteractiveUtils", "FiniteDifferences"]
